pub mod auth;
pub mod test_support;
pub mod token_data;

mod gateway_auth;
mod oauth;
mod outbound_proxy;
mod pkce;

pub use codex_config::types::AuthCredentialsStoreMode;
pub use codex_http_client::BuildCustomCaTransportError as BuildLoginHttpClientError;

pub use auth::AuthChangeState;
pub use auth::AuthConfig;
pub use auth::AuthDotJson;
pub use auth::AuthHeaders;
pub use auth::AuthKeyringBackendKind;
pub use auth::AuthManager;
pub use auth::AuthManagerConfig;
pub use auth::AuthManagerInitializationError;
pub use auth::AuthRuntimeConfig;
pub use auth::CODEX_ACCESS_TOKEN_ENV_VAR;
pub use auth::CODEX_API_KEY_ENV_VAR;
pub use auth::CodexAuth;
pub use auth::ExternalAuth;
pub use auth::ExternalAuthFuture;
pub use auth::ExternalAuthRefreshContext;
pub use auth::ExternalAuthRefreshReason;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::UnauthorizedRecovery;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::is_workload_identity_selected;
pub use auth::load_auth_dot_json;
pub use auth::login_with_api_key;
pub use auth::login_with_bedrock_access_keys;
pub use auth::login_with_bedrock_api_key;
pub use auth::logout;
pub use auth::read_openai_api_key_from_env;
pub use auth::save_auth;
pub use outbound_proxy::AuthRouteConfig;
pub use token_data::TokenData;

pub use gateway_auth::GatewayAuthConfig;
pub use gateway_auth::GatewayAuthError;
pub use gateway_auth::GatewayAuthManager;
pub use gateway_auth::GatewayAuthStatus;
pub use gateway_auth::GatewayAuthStatusChange;
pub use gateway_auth::GatewayLoginControl;
pub use gateway_auth::subscribe_gateway_auth_status;
